### ISSUE TITLE
[feat] 장바구니 ui 

### ISSUE THREAD

**Issue by leeeha** [GOSOPT-CDS-BAEMIN/Android#5]
## ISSUE

- 장바구니 UI 구현 
- 리디자인: 다른 매장의 음식들을 한꺼번에 담을 수 있도록 

## To-Do

- [x] 헤더 상단에 고정 (이전 버튼, 타이틀, 홈 버튼, 함께주문 버튼) 
- [x] 장바구니에 담은 매장 목록, 매장별 음식 목록 조회 -> 중첩 리사이클러뷰 
- [x] 매장별 음식 개수, 총 금액, 주문하기 버튼 (최소주문금액 채워야 버튼 활성화) 
- [x] 총 주문금액, 배달팁 포함한 결제예정금액 표시 
- [x] (주)우아한형제들 텍스트 표시 
- [x] NestedScrollView로 리사이클러뷰와 다른 뷰들 감싸서 한번에 스크롤 하기 
- [ ] 배달, 포장 라디오 버튼 커스텀 -> 선택한 항목에 따라 텍스트 바뀌도록 
- [ ] 최종 주문하기 버튼에 상품 개수, 총 금액 표시
- [ ] 여러 매장 선택 후 한꺼번에 삭제 
- [ ] 매장 개별 삭제 
- [ ] 음식 개별 삭제 
- [ ] 음식 수량 변경 
- [ ] 음식 개별 선택 
- [ ] 메뉴 추가 버튼 (업체 상세로 돌아감), 이전 버튼, 홈 버튼 -> 화면 네비게이션 
- [ ] 주문하기 버튼 누르면 장바구니에서 해당 데이터 삭제
